### ISSUE TITLE
Move Components from Storybook Lib to Gatsby Project

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#105]
- [x] Buttons - Fix fonts
- [x] Cards - Done
- [x]  Logos - Done
- [x]  Icons - Add more sizes and colors
- [x]  NavMenu - Update mobile version
- [x]  Text - Not finished yet
- [x]  TextInput - Not finished yet

**Comment by robertsbaer** [comment]
Done

**Comment by robertsbaer** [comment]
@erinkelley27 Would you also like me to add DatePicker to our components

**Comment by erinkelley27** [comment]
@robertsbaer I didn't see them in the develop branch of the other component library, so let me take a look at them.
