### ISSUE TITLE
Component: Collection List

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#123]
@mdrisco4 has a great start on this component in the old component library! Touch base with him to get started.

Desktop:
<img width="679" alt="Screen Shot 2020-02-07 at 10 43 55 AM" src="https://user-images.githubusercontent.com/38398204/74043195-f0accd00-4996-11ea-9478-55995c20c88f.png">
<img width="680" alt="Screen Shot 2020-02-07 at 10 44 05 AM" src="https://user-images.githubusercontent.com/38398204/74043198-f1ddfa00-4996-11ea-88c8-a13cbb367617.png">
<img width="679" alt="Screen Shot 2020-02-07 at 10 44 13 AM" src="https://user-images.githubusercontent.com/38398204/74043203-f30f2700-4996-11ea-9376-30d8ed6c1c63.png">
<img width="681" alt="Screen Shot 2020-02-07 at 10 44 20 AM" src="https://user-images.githubusercontent.com/38398204/74043209-f4405400-4996-11ea-8283-d4e1a9109642.png">

Mobile:
<img width="374" alt="Screen Shot 2020-02-07 at 10 43 05 AM" src="https://user-images.githubusercontent.com/38398204/74043221-f7d3db00-4996-11ea-8b88-5035458a0dc9.png">
<img width="372" alt="Screen Shot 2020-02-07 at 10 43 15 AM" src="https://user-images.githubusercontent.com/38398204/74043226-f9050800-4996-11ea-8f51-838ae1c020b6.png">
<img width="373" alt="Screen Shot 2020-02-07 at 10 43 23 AM" src="https://user-images.githubusercontent.com/38398204/74043229-f99d9e80-4996-11ea-9094-2443c80fdba0.png">
<img width="373" alt="Screen Shot 2020-02-07 at 10 43 30 AM" src="https://user-images.githubusercontent.com/38398204/74043231-facecb80-4996-11ea-9a3a-9eb4cda037ea.png">

**Comment by jserrao** [comment]
Closed by #114 merge
