### ISSUE TITLE
Component: Collection Header

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#124]
Desktop:
<img width="679" alt="Screen Shot 2020-02-07 at 10 51 27 AM" src="https://user-images.githubusercontent.com/38398204/74043674-d0314280-4997-11ea-9727-66b01a8959a3.png">

Mobile:
<img width="371" alt="Screen Shot 2020-02-07 at 10 50 24 AM" src="https://user-images.githubusercontent.com/38398204/74043615-b68ffb00-4997-11ea-8922-97c8310cc95e.png">

**Comment by jserrao** [comment]
@erinkelley27 - what branch is this on?

**Comment by mamady310** [comment]
@jserrao I'm sorry I need clarification. What do you mean by "you need to get this arrow inline with the heading"..is it that the arrow isn't centered horizontally with the header?

**Comment by mamady310** [comment]
@erinkelley27 added margin bottom to arrow

**Comment by mamady310** [comment]
@jserrao followed the directions for "the release" on both collection-header and collection-header-desktop branches. Was able to run storybook and gatsby develop.

**Comment by jserrao** [comment]
Looking good @mamady310
