### ISSUE TITLE
Component: Dress List Item

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#125]
Desktop:
<img width="327" alt="Screen Shot 2020-02-07 at 10 53 13 AM" src="https://user-images.githubusercontent.com/38398204/74043847-1b4b5580-4998-11ea-8ea9-ab2b7171eb81.png">

Mobile:
<img width="325" alt="Screen Shot 2020-02-07 at 10 54 14 AM" src="https://user-images.githubusercontent.com/38398204/74043916-34540680-4998-11ea-8697-504e42eeea63.png">

**Comment by jserrao** [comment]
#125 closed this.
