### ISSUE TITLE
Component: Dress List

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#127]
Desktop:
<img width="264" alt="Screen Shot 2020-02-07 at 10 55 05 AM" src="https://user-images.githubusercontent.com/38398204/74044035-6a918600-4998-11ea-93a9-adb11bc1f58c.png">

Mobile:
<img width="268" alt="Screen Shot 2020-02-07 at 10 55 38 AM" src="https://user-images.githubusercontent.com/38398204/74044040-6d8c7680-4998-11ea-8144-ebbdc45442c5.png">

**Comment by jserrao** [comment]
This was closed by #125
