### ISSUE TITLE
Spring 2017 Content Upload

### ISSUE THREAD

**Issue by jserrao** [jserrao/modern-trousseau-gatsby#145]
Luna Bleu Gown collection was Spring 2017:
https://www.moderntrousseau.com/luna-bleu-collection/

Get all these into Contentful.

**Comment by Cherezmz** [comment]
@jserrao 

John, 

we discussed it with Mamady and she has already added this collection to Contentful. But we need more input here because there is no any gown in this collection from 2017.

**Comment by jserrao** [comment]
@Cherezmz + @mamady310 - luna bleu collection IS the Spring 2017 collection. They did a collaboration that season.

**Comment by Cherezmz** [comment]
@jserrao 
@mamady310 added this collection as spring 2017. So, it is ok.

**Comment by jserrao** [comment]
Content uploaded.
