### ISSUE TITLE
Fall 2020 Collection

### ISSUE THREAD

**Issue by jserrao** [jserrao/modern-trousseau-gatsby#146]
@Cherezmz - get the Fall 2020 collection into Contentful like you were doing yesterday.

Imagery:
https://drive.google.com/drive/folders/1rsN2n1kAY_fnwJ6pK6hFSZsyxV0b815Q?usp=sharing

Gown naming guidance:
Adrian, Avita, Fabia (image 93), Cesar, Cyrus (image 43), Atticus (image 09) Valentina (image 34), Raphael (image 67)

Gown Description guidance:
client will add these in once we give her access

**Comment by Cherezmz** [comment]
@jserrao 

Done

**Comment by jserrao** [comment]
@Cherezmz - thanks, check in with mamady, see if she needs help on:
https://github.com/jserrao/modern-trousseau-gatsby/issues/145

You guys could do that one together
