### ISSUE TITLE
Individual Gown Page

### ISSUE THREAD

**Issue by mdrisco4** [jserrao/modern-trousseau-gatsby#162]
This is the page that displays individual gowns with a description on the desktop version and a + sign button to see details in the mobile version

**Comment by jserrao** [comment]
You got this page done last sprint @mdrisco4. It would be good if you did an audit of what's left to accomplish given how far you've gotten.

**Comment by mdrisco4** [comment]
@jserrao I will take a closer look at this tonight and see where everything stands.  Still need to touch base with Jenny when she gets to it about the button Jose was working on as well.

**Comment by jserrao** [comment]
@mdrisco4 - sounds good thanks.
