### ISSUE TITLE
Integrate Storybook into Gatsby

### ISSUE THREAD

**Issue by jmripper** [jserrao/modern-trousseau-gatsby#34]

**Comment by robertsbaer** [comment]
Create an NPM of the storybook we have created already.
How will they be used once we install them onto our new project.

**Comment by jserrao** [comment]
@robertsbaer - I think the plan is no NPM module? Just making sure we have it down somewhere.

**Comment by robertsbaer** [comment]
Will no longer use an NPM.

I copied components into the gatsby-storybook-starter template 
which has both Gatsby (G) and Storybook (SB) dependencies.

I copied the DatePicker folder from the original SB project and everything worked fined within SB and G.
I then copied Card folder and it broke the site. It was missing the Icon folder. Remained broken. Icon needed the dependencies installed.

**Comment by robertsbaer** [comment]
The instance of each component must be called.

**Comment by jserrao** [comment]
Refer to #33  👍 https://github.com/jserrao/modern-trousseau-gatsby/issues/33
