### ISSUE TITLE
Bride Model

### ISSUE THREAD

**Issue by jcasado6** [jserrao/modern-trousseau-gatsby#35]

**Comment by jcasado6** [comment]
Two men enter, one man leave

**Comment by jserrao** [comment]
@jcasado6 + @Adam-DeLessio - based on client feedback, I'm deleting the bride model. It's good in theory but in practice, they only want to be emailed the bride's information as a sales lead, not storing the data into our site.

And even if they did want to store the data, we'd use something like a CRM - maybe salesforce? - to do it. A CMS could do this job, it just doesnt make a lot of sense.
