### ISSUE TITLE
Store Model

### ISSUE THREAD

**Issue by jcasado6** [jserrao/modern-trousseau-gatsby#38]

**Comment by karadikid** [comment]
Fields:

Flagships
Name: String
Street Address: String
City: String
State: String
Phone Number: Int
Zip: Int
Email: String
Twitter_Handle: String. - Clarify (Link)
Image: ImageType

**Comment by jserrao** [comment]
https://app.contentful.com/spaces/2n4rer1mpqy8/content_types/store/fields
