### ISSUE TITLE
Put together Book Appointment Page

### ISSUE THREAD

**Issue by jmripper** [jserrao/modern-trousseau-gatsby#41]

**Comment by jserrao** [comment]
@K0LdW0rLd + @jcasado6 - I want the two of your to work on this together. You need to think through the data, which components to use, how they map to the model, and what your output will look like (text email).

Reference the model creation: https://github.com/jserrao/modern-trousseau-gatsby/issues/47

**Comment by jserrao** [comment]
Not going to make Sprint 2 on this.

**Comment by jserrao** [comment]
Too broad, closing. But many of the components got made from this...which was cool.
