### ISSUE TITLE
Put together About Page Design

### ISSUE THREAD

**Issue by jmripper** [jserrao/modern-trousseau-gatsby#43]

**Comment by jserrao** [comment]
@jmripper - this is a high priority.  We need to scope this page out a bit.

We don't have good design guidance, so let's take a shot at it based on the old site:
https://www.moderntrousseau.com/about/

The 'Our Story' part of the site has some good stuff in there - a couple videos, text boxes. Work with @jcasado6 to come up with a data model and general wireframe. Post into this ticket.

**Comment by jserrao** [comment]
I'm reassigning this to myself, going to make something we can go off in Figma and update this task

**Comment by jserrao** [comment]
@jcasado6 advice after reviewing the old site:

> @jserrao @jmripper The options we are giving the client for the about us section are as follows...
> 
> A landing page with a title, description, and image
> Two other pages that will be in the drop down selection, Careers page & and The making of a MT gown.
> We will need more information on what the content the client wants in that careers page.
> The making of a MT gown will be kept the same IE title, video, and link to youtube channel.
> Let me know your thoughts and please get back to me with client needs as soon as possible. Thanks.

**Comment by jmripper** [comment]
this sounds good to me. I can work on building it out if no one else is. @jserrao

**Comment by jserrao** [comment]
@jmripper - do you have enough to go off of? We could collaborate on this one if you need design guidance. First step is probably making a wireframe.
