### ISSUE TITLE
Learning - High Level: How Contentful & Gatsby Work Together (or dont...)

### ISSUE THREAD

**Issue by jcasado6** [jserrao/modern-trousseau-gatsby#63]

**Comment by jserrao** [comment]
Deliverable on this ticket is a brief summary - could just be a series of bullet points that covers the main ideas.

**Comment by jserrao** [comment]
Remember, learning tasks can include learning that the tool sucks. Totally valid.

**Comment by jserrao** [comment]
@jcasado6 - excellent work on this one.
