### ISSUE TITLE
About Page Model

### ISSUE THREAD

**Issue by jserrao** [jserrao/modern-trousseau-gatsby#84]
On the back-end, admin's need a page model where they can input information about the organization. Please coordinate with the front-end team on the needs for this page.

**Comment by jserrao** [comment]
@jcasado6 - please take lead on this one, we probably need to coordinate exactly what goes on this page.

**Comment by jcasado6** [comment]
Will do

**Comment by jcasado6** [comment]
@jserrao @jmripper  The options we are giving the client for the about us section are as follows...
1. A landing page with a title, description, and image
2. Two other pages that will be in the drop down selection, Careers page & and The making of a MT gown.
3. We will need more information on what the content the client wants in that careers page.
4. The making of a MT gown will be kept the same IE title, video, and link to youtube channel. 
Let me know your thoughts  and please get back to me with client needs as soon as possible. Thanks.

**Comment by jserrao** [comment]
@jcasado6 - I'm moving this to sprint 2 - as this will likely require coordination with front-end to get right.

I implemented a simple page model here:
https://app.contentful.com/spaces/2n4rer1mpqy8/content_types/page/fields

This will have to be adjusted so that it can be used across the use cases you outlined above. We can talk more about this.

**Comment by jserrao** [comment]
Page model was created by yours truly, still not sure how we're using it.
