### ISSUE TITLE
Component: Icon

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#86]
<img width="85" alt="Screen Shot 2020-02-04 at 9 08 46 PM" src="https://user-images.githubusercontent.com/38398204/73804805-f2a63e80-4792-11ea-9df9-18c364a0031c.png">
<img width="86" alt="Screen Shot 2020-02-04 at 9 08 52 PM" src="https://user-images.githubusercontent.com/38398204/73804807-f4700200-4792-11ea-9105-db1ba6c5a383.png">
<img width="142" alt="Screen Shot 2020-02-04 at 9 09 32 PM" src="https://user-images.githubusercontent.com/38398204/73804809-f5a12f00-4792-11ea-8003-958b67827aae.png">
<img width="144" alt="Screen Shot 2020-02-04 at 9 09 41 PM" src="https://user-images.githubusercontent.com/38398204/73804810-f76af280-4792-11ea-9968-a8c7eb4ab0f5.png">
<img width="171" alt="Screen Shot 2020-02-04 at 9 09 48 PM" src="https://user-images.githubusercontent.com/38398204/73804813-f89c1f80-4792-11ea-9f82-edbbb9c88647.png">
<img width="60" alt="Screen Shot 2020-02-04 at 9 09 58 PM" src="https://user-images.githubusercontent.com/38398204/73804816-f9cd4c80-4792-11ea-8630-40325258d504.png">
<img width="355" alt="Screen Shot 2020-02-04 at 9 10 13 PM" src="https://user-images.githubusercontent.com/38398204/73804819-fc2fa680-4792-11ea-98ab-b7763d35abb3.png">
<img width="71" alt="Screen Shot 2020-02-04 at 9 10 33 PM" src="https://user-images.githubusercontent.com/38398204/73804824-fe920080-4792-11ea-8e38-bee910de5ad8.png">
<img width="74" alt="Screen Shot 2020-02-04 at 9 10 37 PM" src="https://user-images.githubusercontent.com/38398204/73804829-ffc32d80-4792-11ea-94a6-e7d7b6593616.png">

**Icon Component**

**Comment by jserrao** [comment]
@erinkelley27 - isnt' this already in there somewhere?

**Comment by erinkelley27** [comment]
@jserrao Yup - closing now.
