### ISSUE TITLE
Component: Nav Bar

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#89]
**Nav Bar Component**

Top Nav Bar for Desktop:
<img width="720" alt="Screen Shot 2020-02-04 at 9 21 05 PM" src="https://user-images.githubusercontent.com/38398204/73805384-8a585c80-4794-11ea-94a4-e0e202589172.png">

Header Nav Bar for Desktop:
<img width="718" alt="Screen Shot 2020-02-04 at 9 23 44 PM" src="https://user-images.githubusercontent.com/38398204/73805429-a52ad100-4794-11ea-82d7-2f9dfd2ab9a7.png">

**Comment by robertsbaer** [comment]
@jmripper in NavMenu.js 
On line 2 add 
`import { BrowserRouter, Link } from "react-router-dom";`
On line 9 add 
`<nav>
    <BrowserRouter>`
On line 42 add a closing tag
`</BrowserRouter>`

**Comment by jserrao** [comment]
Closed by #140
