### ISSUE TITLE
Component: Hero

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#90]
**Hero Component**

Desktop Hero:
<img width="717" alt="Screen Shot 2020-02-04 at 9 27 49 PM" src="https://user-images.githubusercontent.com/38398204/73805638-4154d800-4795-11ea-98c6-f8f12760ee3a.png">

Mobile Hero:
<img width="375" alt="Screen Shot 2020-02-04 at 9 25 35 PM" src="https://user-images.githubusercontent.com/38398204/73805542-f4710180-4794-11ea-8462-fd56e33768a2.png">

**Comment by jserrao** [comment]
Closed by #169
