### ISSUE TITLE
Component: Hero Slider

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#91]
**Hero Slider**
This component will include the image, slider functionality and the three dots at the bottom. It does not need to include the caption or the button. Those components will be added to the molecular Hero component.

Desktop:
<img width="782" alt="Screen Shot 2020-02-04 at 9 29 02 PM" src="https://user-images.githubusercontent.com/38398204/73805824-ba542f80-4795-11ea-83e0-4073b5cdb82e.png">
<img width="782" alt="Screen Shot 2020-02-04 at 9 30 08 PM" src="https://user-images.githubusercontent.com/38398204/73805833-c17b3d80-4795-11ea-8174-2496c1ad129c.png">
<img width="783" alt="Screen Shot 2020-02-04 at 9 29 51 PM" src="https://user-images.githubusercontent.com/38398204/73805834-c2ac6a80-4795-11ea-8a03-f2375264decf.png">

Mobile:
<img width="376" alt="Screen Shot 2020-02-04 at 9 32 27 PM" src="https://user-images.githubusercontent.com/38398204/73805883-e8397400-4795-11ea-834d-60e44cabec3a.png">
<img width="375" alt="Screen Shot 2020-02-04 at 9 32 36 PM" src="https://user-images.githubusercontent.com/38398204/73805887-ea033780-4795-11ea-9f6f-96a5327de1a6.png">
<img width="376" alt="Screen Shot 2020-02-04 at 9 32 44 PM" src="https://user-images.githubusercontent.com/38398204/73805890-ebccfb00-4795-11ea-8d14-e372f216a635.png">

**Comment by jserrao** [comment]
Closed by #169
