### ISSUE TITLE
Component: Hero Caption

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#92]
**Hero Caption Component**

<img width="441" alt="Screen Shot 2020-02-04 at 9 34 08 PM" src="https://user-images.githubusercontent.com/38398204/73805951-1d45c680-4796-11ea-8de7-1a6125386be7.png">

**Comment by jserrao** [comment]
@erinkelley27 - what branch/PR closed this? Can you link it in the sidebar?
