### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#93]
**Button Component**

<img width="129" alt="Screen Shot 2020-02-04 at 9 35 26 PM" src="https://user-images.githubusercontent.com/38398204/73806064-76adf580-4796-11ea-8dff-8a7067d5459f.png">
<img width="127" alt="Screen Shot 2020-02-04 at 9 35 35 PM" src="https://user-images.githubusercontent.com/38398204/73806065-77df2280-4796-11ea-95a1-26266c7c4aad.png">
<img width="128" alt="Screen Shot 2020-02-04 at 9 35 44 PM" src="https://user-images.githubusercontent.com/38398204/73806068-79104f80-4796-11ea-9b3b-4806b20ffb6e.png">
<img width="181" alt="Screen Shot 2020-02-04 at 9 36 15 PM" src="https://user-images.githubusercontent.com/38398204/73806069-7a417c80-4796-11ea-9e8c-c7c767a721ad.png">
<img width="175" alt="Screen Shot 2020-02-04 at 9 36 25 PM" src="https://user-images.githubusercontent.com/38398204/73806072-7ada1300-4796-11ea-86f6-411596daecc1.png">

**Comment by jserrao** [comment]
@erinkelley27 + @jmripper - what branch / PR closed this?
