### ISSUE TITLE
Component: Card

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#96]
<img width="717" alt="Screen Shot 2020-02-04 at 9 42 44 PM" src="https://user-images.githubusercontent.com/38398204/73806390-5b8fb580-4797-11ea-8fdd-ccd9d6ee2257.png">
<img width="722" alt="Screen Shot 2020-02-04 at 9 42 55 PM" src="https://user-images.githubusercontent.com/38398204/73806392-5c284c00-4797-11ea-975a-89830b04804c.png">
<img width="741" alt="Screen Shot 2020-02-04 at 9 43 04 PM" src="https://user-images.githubusercontent.com/38398204/73806395-5d597900-4797-11ea-884e-b36784a38597.png">

**Comment by Creizai** [comment]
This doesn't need to be done, already in under card component.

**Comment by erinkelley27** [comment]
@Creizai It doesn't look like these are taking on colors. Maybe you can assign yourself to this issue and fix that problem.

**Comment by Creizai** [comment]
Will do!

**Comment by Creizai** [comment]
Please close this request, Jenny has completed this and already merged the updated version before I got mine done T_T
