### ISSUE TITLE
Component: Owner Quote

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#97]
**Owner Quote Component**

Desktop:
<img width="716" alt="Screen Shot 2020-02-04 at 9 44 20 PM" src="https://user-images.githubusercontent.com/38398204/73806484-9db8f700-4797-11ea-81ce-0860c51150c1.png">

Mobile:
<img width="375" alt="Screen Shot 2020-02-04 at 9 44 36 PM" src="https://user-images.githubusercontent.com/38398204/73806489-a14c7e00-4797-11ea-832f-df58cc9247a0.png">

**Comment by Creizai** [comment]
This was completed but also there is a duplicate by @K0LdW0rLd titled designer card.
