### ISSUE TITLE
Component: Collection

### ISSUE THREAD

**Issue by erinkelley27** [jserrao/modern-trousseau-gatsby#98]
**Collection Component**

Desktop:
<img width="681" alt="Screen Shot 2020-02-04 at 9 46 25 PM" src="https://user-images.githubusercontent.com/38398204/73806605-f1c3db80-4797-11ea-8c33-6b8228042647.png">

Mobile:
<img width="370" alt="Screen Shot 2020-02-04 at 9 46 43 PM" src="https://user-images.githubusercontent.com/38398204/73806610-f5eff900-4797-11ea-9fda-153d37ec37fe.png">

**Comment by jserrao** [comment]
Closed by #114
